version: '3'
networks:
  backend:
    driver: bridge
services:
  php:
    build: .
    volumes:
      - .:/app
      - ../libs:/libs
#    ports:
#      - "1234:1234"
    environment:
      - Env=prod
    tty: true
    working_dir: /app
    networks:
      - backend